alias cat=bat
alias ls='ls --color=auto'
alias ll='ls -alF'
alias la='ls -A'
alias l='ls -CF'
alias grep='grep --color=auto'
alias diff='colordiff'


alias download="wget --random-wait -r -p --no-parent -e robots=off -U mozilla"
alias server="ifconfig | grep inet && python3 -m http.server"

alias apt="sudo nala"
alias maxvol="pactl set-sink-volume @DEFAULT_SINK@ 150%"
export FZF_DEFAULT_OPTS="--preview 'bat --color=always {}'"
export FZF_DEFAULT_COMMAND="fdfind --type f"